services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ceb
      POSTGRES_USER: ceb
      POSTGRES_PASSWORD: ceb
    ports:
      - "5411:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
