# Generated by Django 5.1.15 on 2026-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('learn', 'learn'), ('diagnostic', 'diagnostic'), ('drill', 'drill'), ('exam', 'exam')], default='learn', max_length=20),
        ),
    ]
