# Generated by Django 5.1.15 on 2026-05-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_tutor_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('chars_used', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_usage', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='voice_voice_year_1f5428_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'year', 'month'), name='uq_voice_usage_per_month')],
            },
        ),
    ]
