# Generated by Django 5.1.15 on 2026-04-19 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('input_type', models.CharField(choices=[('number', 'Number'), ('mcq', 'MCQ'), ('symbol', 'Symbol'), ('decomposition', 'Decomposition'), ('point_on_line', 'Point on number line'), ('drag_order', 'Drag to order')], default='number', max_length=20)),
                ('template', models.JSONField()),
            ],
            options={
                'ordering': ['difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_params', models.JSONField(default=dict)),
                ('student_answer', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_sessions.session')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercisetemplate')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSkillWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_weights', to='skills.skill')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_weights', to='exercises.exercisetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='exercisetemplate',
            name='skills',
            field=models.ManyToManyField(related_name='templates', through='exercises.TemplateSkillWeight', to='skills.skill'),
        ),
        migrations.AddConstraint(
            model_name='templateskillweight',
            constraint=models.UniqueConstraint(fields=('template', 'skill'), name='uq_template_skill'),
        ),
        migrations.AddConstraint(
            model_name='templateskillweight',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 1)), name='weight_range_0_1'),
        ),
        migrations.AddConstraint(
            model_name='exercisetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 3)), name='difficulty_range'),
        ),
    ]
