# Generated by Django 5.1.15 on 2026-04-14 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('template', models.JSONField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='skills.skill')),
            ],
            options={
                'ordering': ['skill_id', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_params', models.JSONField(default=dict)),
                ('student_answer', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_sessions.session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skill')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercisetemplate')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercisetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 3)), name='difficulty_range'),
        ),
    ]
