# Generated by Django 5.1.15 on 2026-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='signature_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
