# Generated by Django 5.1.15 on 2026-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_attempt_signature_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='error_tag',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='input_type',
            field=models.CharField(choices=[('number', 'Number'), ('mcq', 'MCQ'), ('mcq_multi', 'MCQ multi-correct'), ('symbol', 'Symbol'), ('binary_equality', 'Binary equality'), ('decomposition', 'Decomposition'), ('point_on_line', 'Point on number line'), ('drag_order', 'Drag to order')], default='number', max_length=20),
        ),
    ]
