"""baseline: skills, students, sessions, attempts

Revision ID: bee383cf0753
Revises:
Create Date: 2026-04-11 01:38:49.788557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bee383cf0753"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("grade", sa.String(length=5), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("mastery_threshold", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("grade", sa.String(length=5), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_templates",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 3", name="valid_difficulty"),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_prerequisites",
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("prerequisite_id", sa.String(length=100), nullable=False),
        sa.CheckConstraint("skill_id != prerequisite_id", name="no_self_prerequisite"),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("skill_id", "prerequisite_id"),
    )
    op.create_table(
        "student_skill_state",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("mastery_level", sa.Float(), nullable=False),
        sa.Column("consecutive_correct", sa.Integer(), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "skill_id"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.String(length=100), nullable=False),
        sa.Column("exercise_template_id", sa.String(length=100), nullable=True),
        sa.Column("exercise_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("student_answer", sa.String(), nullable=True),
        sa.Column("correct_answer", sa.String(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("responded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_template_id"],
            ["exercise_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attempts")
    op.drop_table("student_skill_state")
    op.drop_table("skill_prerequisites")
    op.drop_table("sessions")
    op.drop_table("exercise_templates")
    op.drop_table("students")
    op.drop_table("skills")
    # ### end Alembic commands ###
