# Generated by Django 5.1.15 on 2026-04-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('mastery_threshold', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['grade', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='skills.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='skills.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(related_name='dependents', through='skills.SkillPrerequisite', to='skills.skill'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.UniqueConstraint(fields=('skill', 'prerequisite'), name='uq_skill_prereq'),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('skill', models.F('prerequisite')), _negated=True), name='no_self_prerequisite'),
        ),
    ]
