import {
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Award,
  BabyIcon,
  BookOpen,
  Check,
  ClipboardList,
  Clock,
  Download,
  CheckCircle2,
  Circle,
  Delete,
  Droplets,
  FileText,
  Flag,
  Flame,
  Flower2,
  GitBranch,
  Home,
  Leaf,
  Lightbulb,
  LineChart,
  Loader2,
  LogOut,
  MessageCircle,
  MessagesSquare,
  Mic,
  MicOff,
  Pause,
  Plus,
  Play,
  Volume2,
  VolumeX,
  RotateCw,
  Send,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Star,
  Target,
  Trash2,
  Trophy,
  User,
  Users,
  X,
  XCircle,
  Zap,
} from "lucide-react"

const ICONS = {
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  audio_lines: AudioLines,
  account_tree: GitBranch,
  assignment: ClipboardList,
  backspace: Delete,
  bolt: Zap,
  book: BookOpen,
  cancel: XCircle,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  child_care: BabyIcon,
  circle: Circle,
  close: X,
  delete: Trash2,
  description: FileText,
  download: Download,
  droplets: Droplets,
  flag: Flag,
  flame: Flame,
  forum: MessagesSquare,
  history: Clock,
  mic: Mic,
  mic_off: MicOff,
  pause: Pause,
  volume_off: VolumeX,
  volume_up: Volume2,
  flower: Flower2,
  home: Home,
  insights: LineChart,
  leaf: Leaf,
  lightbulb: Lightbulb,
  logout: LogOut,
  play_arrow: Play,
  progress_activity: Loader2,
  refresh: RotateCw,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  supervisor_account: Users,
  target: Target,
  trash: Trash2,
  trophy: Trophy,
  tune: SlidersHorizontal,
  user: User,
  award: Award,
}

export default function Icon({ name, fill, className = "", size = 18 }) {
  const Cmp = ICONS[name] ?? Circle
  return (
    <Cmp
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={fill ? 2.2 : 1.75}
      fill={fill ? "currentColor" : "none"}
    />
  )
}
