# Generated by Django 5.1.15 on 2026-04-19 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(default='curieux', max_length=24)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('daily_goal', models.PositiveSmallIntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
            options={
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'code'), name='uq_student_achievement')],
            },
        ),
        migrations.CreateModel(
            name='StudentSkillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_xp', models.FloatField(default=0.0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_states', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'skill'), name='uq_student_skill'), models.CheckConstraint(condition=models.Q(('skill_xp__gte', 0), ('skill_xp__lte', 30.0)), name='skill_xp_range')],
            },
        ),
    ]
