# Generated by Django 5.1.15 on 2026-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_voice',
            field=models.CharField(choices=[('female', 'Voix féminine'), ('male', 'Voix masculine')], default='female', max_length=8),
        ),
    ]
