# Generated by Django 5.1.15 on 2026-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskillstate',
            name='status',
            field=models.CharField(choices=[('not_started', 'Pas commencé'), ('in_progress', 'En cours'), ('mastered', 'Maîtrisé'), ('needs_review', 'À revoir')], default='not_started', max_length=16),
        ),
    ]
