# Generated by Django 5.1.15 on 2026-04-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentskillstate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskillstate',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentskillstate',
            name='review_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
